version: "3"

services:
  big_iot_gw:
    volumes:
      - .:/go/src/github.com/thingful/big-iot-gateway
    build:
      context: .
    image: thingful/big-iot-gateway
    ports:
      - '8080:8080'
    command: /app/big-iot-gateway